apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: shadowscan-ai-runtime-example
spec:
  kprobes:
    - call: "security_file_open"
      syscall: false
      args:
        - index: 0
          type: "file"
      selectors:
        - matchActions:
            - action: Post
    - call: "tcp_v4_connect"
      syscall: false
      args:
        - index: 0
          type: "sock"
        - index: 1
          type: "sockaddr"
      selectors:
        - matchActions:
            - action: Post
