"""Render the configuration reference of every built-in connector from its class.

``docs/connectors/reference.md`` is generated by this module so that the
documented keys cannot drift from ``config_keys``. Regenerate it after changing
a connector's keys, description, requirements or offline formats::

    python -m tools.connector_reference          # rewrite the page
    python -m tools.connector_reference --check  # exit 1 when it is stale
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from shadowscan.config import accepted_connector_keys
from shadowscan.connectors import builtin_connector_names, get_connector_class

REFERENCE = Path(__file__).resolve().parents[1] / "docs" / "connectors" / "reference.md"
SURFACE_TITLES = {
    "code": "Code",
    "identity": "Identity",
    "gateway": "Gateway",
    "lowcode": "Low-code",
    "saas": "SaaS",
    "cloud": "Cloud",
    "endpoint": "Endpoint",
    "network": "Network",
    "runtime": "Runtime",
}
# Braces too: the docs build's attr_list extension reads "{...}" as attributes.
_MARKDOWN_SPECIAL = re.compile(r"([\\*_\[\]{}|])")
_CODE_SPAN = re.compile(r"(`[^`]+`)")


def _plain(text: str) -> str:
    """Escape Markdown outside code spans; Python-Markdown has no backslash escape for "<"."""
    return _MARKDOWN_SPECIAL.sub(r"\\\1", text).replace("<", "&lt;").replace(">", "&gt;")


def _text(value: object) -> str:
    """Literal Markdown for a description on one line.

    Balanced code spans are kept verbatim (a pipe inside one does not split
    a table cell); everything else is escaped, and so is any text with an
    unbalanced backtick.
    """
    flat = " ".join(str(value).split())
    if flat.count("`") % 2:
        return _plain(flat).replace("`", "\\`")
    parts = _CODE_SPAN.split(flat)
    return "".join(part if index % 2 else _plain(part) for index, part in enumerate(parts))


def render() -> str:
    """Return the reference page for the built-in connectors, grouped by surface."""
    by_surface: dict[str, list[str]] = {}
    for name in sorted(builtin_connector_names()):
        by_surface.setdefault(name.split(".", 1)[0], []).append(name)
    unknown = set(by_surface) - set(SURFACE_TITLES)
    if unknown:
        raise ValueError(f"no section title for connector surfaces: {sorted(unknown)}")
    lines = [
        "# Connector configuration reference",
        "",
        "<!-- Generated by `python -m tools.connector_reference`; do not edit by hand. -->",
        "",
        "Every key each built-in connector declares, as `shadowscan connectors` lists it,",
        "then the keys its entry also accepts without describing them, such as `label`",
        "and aliases. Any other key is rejected when the configuration is parsed.",
        "Keys described as *offline* apply when the connector reads an export (`input`).",
        "The connector guides explain permissions, least-privilege scopes and",
        "the evidence each connector reports.",
    ]
    for surface, title in SURFACE_TITLES.items():
        names = by_surface.get(surface)
        if not names:
            continue
        lines += ["", f"## {title}"]
        for name in names:
            cls = get_connector_class(name)
            keys = dict(cls.config_keys)
            for key, description in cls.shared_config_keys.items():
                keys.setdefault(key, description)
            lines += ["", f"### `{name}`", "", _text(cls.description)]
            details = []
            if cls.requires:
                details.append("Requires: " + ", ".join(f"`{package}`" for package in cls.requires) + ".")
            if cls.offline_formats:
                details.append(f"Offline input: {_text(cls.offline_formats)}.")
            if details:
                lines += ["", " ".join(details)]
            lines += ["", "| Key | Description |", "| --- | --- |"]
            lines += [f"| `{key}` | {_text(description)} |" for key, description in keys.items()]
            accepted = accepted_connector_keys(name) or frozenset()
            extra = sorted(accepted - set(keys))
            if extra:
                lines += ["", "Also accepted: " + ", ".join(f"`{key}`" for key in extra) + "."]
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    if argv not in ([], ["--check"]):
        print("usage: python -m tools.connector_reference [--check]", file=sys.stderr)
        return 2
    page = render()
    if argv == ["--check"]:
        if not REFERENCE.is_file() or REFERENCE.read_text(encoding="utf-8") != page:
            print(f"{REFERENCE} is stale; run python -m tools.connector_reference", file=sys.stderr)
            return 1
        return 0
    REFERENCE.write_text(page, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
