"""Render the threat and control mapping reference from the packaged catalogs.

``docs/concepts/mappings-reference.md`` is generated by this module so that the
documented catalogs and rules cannot drift from ``shadowscan/mappings/data``.
Regenerate it after changing a catalog or a rule::

    python -m tools.mapping_reference          # rewrite the page
    python -m tools.mapping_reference --check  # exit 1 when it is stale
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from shadowscan.mappings import MappingIndex, load_mappings
from shadowscan.mappings.schema import RULE_FILES, Catalog, Condition, Rule

REFERENCE = Path(__file__).resolve().parents[1] / "docs" / "concepts" / "mappings-reference.md"
KIND_TITLES = {"threat": "Threat rules", "layer": "Layer rules", "control": "Control rules"}
# Braces too: the docs build's attr_list extension reads "{...}" as attributes.
_MARKDOWN_SPECIAL = re.compile(r"([\\`*_\[\]{}|])")
_CONDITION_LABELS = (
    ("tags_any", "tag"),
    ("capabilities_any", "capability"),
    ("kinds_any", "kind"),
    ("surfaces_any", "surface"),
    ("oversight_any", "`metadata.autonomy.oversight`"),
    ("registry_status_any", "`metadata.registry_reconciliation.status`"),
)


def _text(value: object) -> str:
    """Literal Markdown for a value on one line; Python-Markdown has no backslash escape for "<"."""
    flat = " ".join(str(value).split())
    return _MARKDOWN_SPECIAL.sub(r"\\\1", flat).replace("<", "&lt;").replace(">", "&gt;")


def _code(value: str) -> str:
    return f"`{value}`"


def _condition(when: Condition) -> str:
    """Every clause of a rule's condition; all of them must hold."""
    clauses = []
    for key, label in _CONDITION_LABELS:
        values = getattr(when, key)
        if values is not None:
            clauses.append(f"{label} {' or '.join(_code(value) for value in sorted(values))}")
    if when.autonomy_floor_at_least is not None:
        clauses.append(f"`metadata.autonomy.floor` at least {when.autonomy_floor_at_least}")
    if when.shadow is not None:
        clauses.append("shadow (not in the inventory)" if when.shadow else "registered in the inventory")
    if when.owner_missing is not None:
        clauses.append("no owner recorded" if when.owner_missing else "owner recorded")
    return "; and ".join(clauses)


def _source(catalog: Catalog) -> str:
    """Where the entries come from, without implying an unreachable source was read."""
    if catalog.verification == "primary":
        return f"Checked against: <{catalog.source_url}>"
    return f"Publication: <{catalog.source_url}> (not consulted directly; entries follow secondary sources)"


def _rule_row(rule: Rule) -> str:
    refs = ", ".join(_code(ref) for ref in rule.refs)
    return f"| {_code(rule.id)} | {_condition(rule.when)} | {refs} | {_text(rule.rationale)} |"


def render(index: MappingIndex | None = None) -> str:
    """Return the reference page for the packaged catalogs and rules."""
    index = index if index is not None else load_mappings()
    lines = [
        "# Mapping catalog reference",
        "",
        "<!-- Generated by `python -m tools.mapping_reference`; do not edit by hand. -->",
        "",
        "Every packaged framework catalog and rule, as `python -m shadowscan.mappings.validate`",
        "checks them. References are evidence references, not compliance determinations,",
        "and the rules are author mappings, not independently reviewed. See",
        "[Threat and control mappings](mappings.md) for how findings use them.",
        "",
        "## Catalogs",
        "",
        "`Checked` is the date a catalog was compiled and its entries last checked.",
        "A `primary` catalog was checked against the source it links. A `secondary`",
        "catalog links the framework's own publication, which could not be consulted;",
        "its entries follow secondary sources.",
        "",
        "| Prefix | Framework | Kind | Verification | Licence | Checked |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    catalogs = sorted(index.catalogs, key=lambda catalog: catalog.prefix)
    lines += [
        f"| {_code(c.prefix)} | {_text(c.name)} | {c.kind} | {c.verification} | {_text(c.licence)}"
        f" | {c.checked} |"
        for c in catalogs
    ]
    for catalog in catalogs:
        lines += ["", f"### {_code(catalog.prefix)}", ""]
        lines += [f"{_text(catalog.name)}, edition {catalog.edition}.", "", _source(catalog)]
        if catalog.notes:
            lines += ["", _text(catalog.notes)]
        lines += ["", "| Reference | Title |", "| --- | --- |"]
        lines += [f"| {_code(entry.ref)} | {_text(entry.title)} |" for entry in catalog.entries]
    lines += [
        "",
        "## Rules",
        "",
        "A rule applies when every clause of its condition holds. Threat and layer rules",
        "feed `metadata.threats`; control rules feed `metadata.controls`.",
    ]
    for name, kind in RULE_FILES.items():
        rules = [rule for rule in index.rules if rule.kind == kind]
        lines += ["", f"### {KIND_TITLES[kind]}", "", f"From `shadowscan/mappings/data/rules/{name}`.", ""]
        lines += ["| Rule | When | References | Rationale |", "| --- | --- | --- | --- |"]
        lines += [_rule_row(rule) for rule in rules]
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    if argv not in ([], ["--check"]):
        print("usage: python -m tools.mapping_reference [--check]", file=sys.stderr)
        return 2
    page = render()
    if argv == ["--check"]:
        if not REFERENCE.is_file() or REFERENCE.read_text(encoding="utf-8") != page:
            print(f"{REFERENCE} is stale; run python -m tools.mapping_reference", file=sys.stderr)
            return 1
        return 0
    REFERENCE.write_text(page, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
