"""Negative-context framework: structured FP suppression for documentation,
example, and generated code paths.

Evidence in these paths is kept but discounted, parallel to how test paths
are treated. Tags and confidence caps make the discounting transparent.
"""

from __future__ import annotations

import pytest

from shadowscan.connectors.code.filesystem import (
    DOCS_MAX_CONFIDENCE,
    DOCS_WEIGHT_SCALE,
    EXAMPLE_PATH_MAX_CONFIDENCE,
    EXAMPLE_PATH_WEIGHT_SCALE,
    GENERATED_MAX_CONFIDENCE,
    GENERATED_WEIGHT_SCALE,
    NegativeContext,
    _is_docs_path,
    _is_example_path,
    _is_generated_path,
    negative_context,
)

# ------------------------------------------------------------------ detectors


class TestDocsPathDetection:
    @pytest.mark.parametrize(
        "path",
        [
            "docs/guide.py",
            "doc/example.py",
            "documentation/setup.py",
            "wiki/page.py",
            "guides/getting-started.py",
            "tutorials/step1.py",
            "src/docs/api.py",
        ],
    )
    def test_docs_paths_detected(self, path):
        assert _is_docs_path(path) is True

    @pytest.mark.parametrize(
        "path",
        [
            "src/main.py",
            "app.py",
            "lib/docs.py",
            "doctor.py",
        ],
    )
    def test_non_docs_paths_not_detected(self, path):
        assert _is_docs_path(path) is False


class TestExamplePathDetection:
    @pytest.mark.parametrize(
        "path",
        [
            "examples/chat.py",
            "example/basic.py",
            "samples/demo.py",
            "sample/app.py",
            "demos/quickstart.py",
            "demo/main.py",
            "quickstart/setup.py",
            "tutorials/basic.py",
            "cookbook/recipe.py",
            "cookbooks/recipe.py",
            "recipes/main.py",
            "boilerplate/app.py",
            "templates/default.py",
            "starter/main.py",
            "starters/basic.py",
        ],
    )
    def test_example_paths_detected(self, path):
        assert _is_example_path(path) is True

    @pytest.mark.parametrize(
        "path",
        [
            "src/main.py",
            "app.py",
            "lib/example_utils.py",
        ],
    )
    def test_non_example_paths_not_detected(self, path):
        assert _is_example_path(path) is False


class TestGeneratedPathDetection:
    @pytest.mark.parametrize(
        "path",
        [
            "src/api_pb2.py",
            "src/api_pb2_grpc.py",
            "src/client.generated.ts",
            "generated/api_pb2.py",
            "Proto/Service.Generated.cs",
        ],
    )
    def test_generated_paths_detected(self, path):
        assert _is_generated_path(path) is True

    @pytest.mark.parametrize(
        "path",
        [
            "src/main.py",
            "app.py",
            "lib/generator.py",
            # A directory name does not make code generated: "codegen" also names
            # an LLM code-generation service.
            "generated/api.py",
            "autogenerated/client.py",
            "codegen/models.py",
            "services/codegen/agent.py",
            # Terraform loads *.auto.tfvars into the deployment.
            "infra/prod.auto.tfvars",
            "src/types.auto.py",
        ],
    )
    def test_non_generated_paths_not_detected(self, path):
        assert _is_generated_path(path) is False


# ----------------------------------------------------------- negative_context


class TestNegativeContext:
    def test_generated_takes_priority_over_docs(self):
        ctx = negative_context("docs/generated/api_pb2.py")
        assert ctx is not None
        assert ctx.reason == "generated-code"

    def test_docs_path(self):
        ctx = negative_context("docs/guide.py")
        assert ctx is not None
        assert ctx.reason == "documentation"
        assert ctx.weight_scale == DOCS_WEIGHT_SCALE
        assert ctx.confidence_cap == DOCS_MAX_CONFIDENCE

    def test_example_path(self):
        ctx = negative_context("examples/chat.py")
        assert ctx is not None
        assert ctx.reason == "example-code"
        assert ctx.weight_scale == EXAMPLE_PATH_WEIGHT_SCALE
        assert ctx.confidence_cap == EXAMPLE_PATH_MAX_CONFIDENCE

    def test_generated_path(self):
        ctx = negative_context("generated/api_pb2.py")
        assert ctx is not None
        assert ctx.reason == "generated-code"
        assert ctx.weight_scale == GENERATED_WEIGHT_SCALE
        assert ctx.confidence_cap == GENERATED_MAX_CONFIDENCE

    def test_normal_path_returns_none(self):
        assert negative_context("src/main.py") is None

    @pytest.mark.parametrize(
        ("rel", "project_root"),
        [
            ("services/templates/agent.py", "services/templates"),
            ("services/docs/agent.py", "services/docs"),
            ("examples/chatbot/app.py", "examples/chatbot"),
            ("recipes/app.py", "recipes"),
        ],
    )
    def test_a_project_root_named_like_docs_or_examples_is_not_discounted(self, rel, project_root):
        assert negative_context(rel, project_root) is None

    def test_docs_and_examples_inside_a_project_are_discounted(self):
        assert negative_context("services/app/examples/demo.py", "services/app").reason == "example-code"
        assert negative_context("services/app/docs/guide.py", "services/app").reason == "documentation"
        assert negative_context("examples/demo.py", ".").reason == "example-code"

    def test_negative_context_is_frozen(self):
        ctx = NegativeContext("test", 0.5, 0.8)
        with pytest.raises(AttributeError):
            ctx.reason = "other"  # type: ignore[misc]


# ------------------------------------------------------- integration via scan


def _project(findings):
    return next((f for f in findings if f.resource_type == "project"), None)


class TestNegativeContextIntegration:
    def test_docs_only_finding_tagged_and_capped(self, tmp_path, run_connector):
        (tmp_path / "docs").mkdir()
        (tmp_path / "docs" / "guide.py").write_text(
            "from openai import OpenAI\n"
            "client = OpenAI()\n"
            "client.chat.completions.create(model='gpt-4', messages=[])\n"
        )
        findings, _ = run_connector("code.filesystem", path=str(tmp_path))
        proj = _project(findings)
        assert proj is not None
        assert "docs-only" in proj.tags
        assert proj.confidence <= DOCS_MAX_CONFIDENCE + 0.001

    def test_example_only_finding_tagged_and_capped(self, tmp_path, run_connector):
        (tmp_path / "examples").mkdir()
        (tmp_path / "examples" / "demo.py").write_text(
            "from openai import OpenAI\n"
            "client = OpenAI()\n"
            "client.chat.completions.create(model='gpt-4', messages=[])\n"
        )
        findings, _ = run_connector("code.filesystem", path=str(tmp_path))
        proj = _project(findings)
        assert proj is not None
        assert "example-code-only" in proj.tags
        assert proj.confidence <= EXAMPLE_PATH_MAX_CONFIDENCE + 0.001

    def test_generated_only_finding_tagged_and_capped(self, tmp_path, run_connector):
        (tmp_path / "generated").mkdir()
        (tmp_path / "generated" / "client.generated.py").write_text(
            "from openai import OpenAI\n"
            "client = OpenAI()\n"
            "client.chat.completions.create(model='gpt-4', messages=[])\n"
        )
        findings, _ = run_connector("code.filesystem", path=str(tmp_path))
        proj = _project(findings)
        assert proj is not None
        assert "generated-code-only" in proj.tags
        assert proj.confidence <= GENERATED_MAX_CONFIDENCE + 0.001

    def test_mixed_normal_and_docs_not_tagged(self, tmp_path, run_connector):
        (tmp_path / "docs").mkdir()
        (tmp_path / "docs" / "guide.py").write_text("from openai import OpenAI\nclient = OpenAI()\n")
        (tmp_path / "app.py").write_text(
            "from openai import OpenAI\n"
            "client = OpenAI()\n"
            "client.chat.completions.create(model='gpt-4', messages=[])\n"
        )
        findings, _ = run_connector("code.filesystem", path=str(tmp_path))
        proj = _project(findings)
        assert proj is not None
        assert "docs-only" not in proj.tags

    def test_negative_context_metadata_recorded(self, tmp_path, run_connector):
        (tmp_path / "examples").mkdir()
        (tmp_path / "examples" / "demo.py").write_text("from openai import OpenAI\nclient = OpenAI()\n")
        (tmp_path / "app.py").write_text(
            "from openai import OpenAI\n"
            "client = OpenAI()\n"
            "client.chat.completions.create(model='gpt-4', messages=[])\n"
        )
        findings, _ = run_connector("code.filesystem", path=str(tmp_path))
        proj = _project(findings)
        assert proj is not None
        assert "negative_contexts" in proj.metadata
        assert "example-code" in proj.metadata["negative_contexts"]

    def test_evidence_annotated_with_negative_context(self, tmp_path, run_connector):
        (tmp_path / "docs").mkdir()
        (tmp_path / "docs" / "guide.py").write_text(
            "from openai import OpenAI\n"
            "client = OpenAI()\n"
            "client.chat.completions.create(model='gpt-4', messages=[])\n"
        )
        findings, _ = run_connector("code.filesystem", path=str(tmp_path))
        proj = _project(findings)
        assert proj is not None
        annotated = [e for e in proj.evidence if e.attributes.get("negative_context") == "documentation"]
        assert len(annotated) > 0

    def test_risk_score_reduced_for_docs_only(self, tmp_path, run_connector):
        from shadowscan.risk import assess

        (tmp_path / "docs").mkdir()
        (tmp_path / "docs" / "guide.py").write_text(
            "from openai import OpenAI\n"
            "client = OpenAI()\n"
            "client.chat.completions.create(model='gpt-4', messages=[])\n"
        )
        findings, _ = run_connector("code.filesystem", path=str(tmp_path))
        proj = _project(findings)
        assert proj is not None
        assert "docs-only" in proj.tags
        proj.risk = assess(proj)
        factor_reasons = [f.description for f in proj.risk.factors]
        assert any("documentation" in r for r in factor_reasons)


@pytest.mark.parametrize("extra", [{"verified_agent": False}, {"lexical_source": True}])
def test_signal_indicator_respects_semantic_verification(extra):
    from shadowscan.connectors.code.filesystem import _ProjectEvidence
    from shadowscan.signatures.loader import Signal, Signature
    from shadowscan.signatures.matcher import Match

    signature = Signature(id="framework.test", name="Test", category="framework")
    match = Match(signature, Signal(type="code", agent_indicator=True), "Agent()", 0.8, extra=extra)
    evidence = _ProjectEvidence([(match, "app.py", None)], discount_tests=True, mcp_tools={})
    assert not evidence.verified_indicator(match)


# ------------------------------------------------ deployable code keeps its evidence

_SHELL_AGENT = (
    "from langchain.agents import create_agent\nfrom langchain.tools import ShellTool\n"
    "shell = ShellTool()\nagent = create_agent(model, tools=[shell])\n"
)


def _service_agent(run_connector, tmp_path, directory):
    service = tmp_path / "services" / directory
    service.mkdir(parents=True)
    (service / "requirements.txt").write_text("langchain\n")
    (service / "agent.py").write_text(_SHELL_AGENT)
    findings, _ = run_connector("code.filesystem", path=str(tmp_path))
    return next(f for f in findings if f.kind.value == "agent")


@pytest.mark.parametrize("directory", ["codegen", "generated", "templates", "recipes", "docs", "examples"])
def test_a_service_named_like_generated_docs_or_examples_keeps_its_capabilities(
    tmp_path, run_connector, directory
):
    from shadowscan.risk import assess

    baseline = _service_agent(run_connector, tmp_path / "baseline", "agentsvc")
    agent = _service_agent(run_connector, tmp_path / "named", directory)
    assert {"code-exec", "tool-use"} <= set(agent.capabilities)
    assert not {"generated-code-only", "docs-only", "example-code-only"} & set(agent.tags)
    assert "negative_contexts" not in agent.metadata
    assert agent.confidence == baseline.confidence
    assert assess(agent).score == assess(baseline).score


def test_generated_file_is_discounted_but_keeps_capabilities(tmp_path, run_connector):
    (tmp_path / "agent.generated.py").write_text(_SHELL_AGENT)
    findings, _ = run_connector("code.filesystem", path=str(tmp_path))
    agent = next(f for f in findings if f.kind.value == "agent")
    assert "generated-code-only" in agent.tags
    assert agent.confidence <= GENERATED_MAX_CONFIDENCE + 0.001
    assert {"code-exec", "tool-use"} <= set(agent.capabilities)
